### ISSUE TITLE
Error 401, Invalid Credentials

### ISSUE THREAD

**Issue by efbe2121** [jsrozner/google_drive_auditer#7]
I got a 401 error, which i couldn't solve. I'm not familiar with Google's API or how Google's Cred works, so i need help or kind of suggestions on what to do. Great tools btw 

Here's the log
```
Running API query with query:
{'maxResults': 1000, 'q': 'trashed=false'}
Traceback (most recent call last):
  File "googdrivecheck.py", line 763, in <module>
    main()
  File "googdrivecheck.py", line 675, in main
    else: run_with_query()
  File "googdrivecheck.py", line 656, in run_with_query
    for file_list in drive.ListFile(query):
  File "/home/mrow/.local/lib/python3.8/site-packages/pydrive/apiattr.py", line 146, in __next__
    result = self._GetList()
  File "/home/mrow/.local/lib/python3.8/site-packages/pydrive/auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/mrow/.local/lib/python3.8/site-packages/pydrive/files.py", line 63, in _GetList
    self.metadata = self.auth.service.files().list(**dict(self)).execute(
  File "/home/mrow/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mrow/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 401 when requesting https://www.googleapis.com/drive/v2/files?maxResults=1000&q=trashed%3Dfalse&alt=json returned "Invalid Credentials">
```

**Comment by jsrozner** [comment]
Hmm, did you follow the instructions in the README, in particular the pydrive link and the setup?

**Comment by efbe2121** [comment]
I did follow everything

**Comment by jsrozner** [comment]
1. clone repo

2. go to https://console.developers.google.com/apis/credentials
3. create a new project
4. create a new Oauth ID
<img width="529" alt="Screen Shot 2022-10-24 at 9 44 59 AM" src="https://user-images.githubusercontent.com/1113285/197584534-0b3ec0f7-88bc-46f9-8428-53690d1bf4ca.png">
5. save the json (tap download) file into the same directory as the code repo, renaming to client_secrets.json

6. rename example_settings.yml -> settings.yml; also `touch saved_credentials.json`

7. (in settings.yml) 
- paste in client_id and client_secret from the output of OAuth client creation
- set myusername to your username (see README)
<img width="202" alt="Screen Shot 2022-10-24 at 10 07 29 AM" src="https://user-images.githubusercontent.com/1113285/197584663-560db5a5-15d0-4279-87f8-302006304252.png">
9. set up the enviroment (for example using conda / pip)
```
conda create --name goog_drive_test
conda activate goog_drive_test
conda install pip
pip install Pipfile
# maybe pip install pyyaml
# maybe pip install pydrive -- not sure why these aren't automatically coming with pip, alas
```
10. run python googdrivecheck.py
11. follow any error messages, eg enabling goog drive API in your project.  

&nbsp;




I verified that this all works as expected just now - starting from cloning the repo and creating a new Oauth ID. Please let me now which step you hadn't done or that wasn't working so I can update the documentation for others!

**Comment by efbe2121** [comment]
Hey jsrozner, thanks for the help!

I just found out the problem, the G-Suite account is in a state of suspended (can't access GDrive neither GDocs), I've tried other tools but return same exact results
I think I'll close this.
